services:
  - type: web
    name: IndicLanguageDetection-1
    runtime: python
    pythonVersion: 3.11.9  # Specify an exact version compatible with TensorFlow 2.12.0
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
