services:
  - type: web
    name: indiclanguagedetection  # Updated to match the deployed URL
    runtime: python
    pythonVersion: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
